export type NcertSubject = 'Polity' | 'History' | 'Geography' | 'Economics' | 'General Science';

export interface NcertQuestion {
  id: string;
  questionText: string;
  options: string[];
  correctOption: number;
  explanation: string;
  /** Written from textbook concepts, never copied from end-of-chapter exercises. */
  type?: 'concept-check' | 'line-detail' | 'application';
}

export interface NcertChapter {
  id: string;
  order: number;
  title: string;
  book: string;
  /** Locator for the official source used to author this revision unit. */
  sourceFocus?: string;
  notes: string[];
  questions: NcertQuestion[];
}

export interface NcertTrack {
  id: string;
  subject: NcertSubject;
  title: string;
  description: string;
  sourceUrl: string;
  chapters: NcertChapter[];
}

const socialScienceUrl = 'https://ncert.nic.in/textbook.php?gess1=0-8';
const geographyUrl = 'https://ncert.nic.in/textbook.php?fess2=1-8';
const seniorSecondaryUrl = 'https://ncert.nic.in/textbook.php?lehs1=3-4';

export const NCERT_TRACKS: NcertTrack[] = [
  {
    id: 'polity', subject: 'Polity', title: 'Indian Polity: NCERT Sprint',
    description: 'Build from citizenship to constitutional institutions in a fixed progression.', sourceUrl: socialScienceUrl,
    chapters: [
      { id: 'polity-1', order: 1, title: 'Citizenship, diversity and equality', book: 'Classes 6–8 Social and Political Life', notes: ['Democracy treats every citizen as politically equal.', 'Equality covers legal status, dignity and equal access to public facilities.', 'Diversity becomes a strength when institutions protect equal rights.'], questions: [{ id: 'nb-p1q1', questionText: 'Which constitutional idea requires the State to treat people equally before the law?', options: ['Liberty', 'Equality', 'Federalism', 'Secularism'], correctOption: 1, explanation: 'Equality before law is a core constitutional guarantee and a frequent static-GK distinction.' }] },
      { id: 'polity-2', order: 2, title: 'Local government and public services', book: 'Classes 6–8 Social and Political Life', notes: ['Panchayats and municipalities address local public needs.', 'Gram Sabha enables direct participation by registered village voters.', 'Public services are funded and administered for collective welfare.'], questions: [{ id: 'nb-p2q1', questionText: 'The Gram Sabha consists primarily of whom?', options: ['Only elected panchayat members', 'All registered voters in a village', 'District officials', 'Members of Parliament'], correctOption: 1, explanation: 'The Gram Sabha is the body of registered voters in the village, not only elected representatives.' }] },
      { id: 'polity-3', order: 3, title: 'The Constitution and the Republic', book: 'Class 9 Democratic Politics', notes: ['The Constitution sets the framework for government and citizen rights.', 'India is a sovereign, socialist, secular, democratic republic.', 'The Preamble expresses constitutional values and goals.'], questions: [{ id: 'nb-p3q1', questionText: 'Which part of the Constitution states its broad ideals and objectives?', options: ['Preamble', 'Schedules', 'Directive Principles only', 'Union List'], correctOption: 0, explanation: 'The Preamble summarises the Constitution’s source of authority, nature of the State and core objectives.' }] },
      { id: 'polity-4', order: 4, title: 'Electoral politics and representation', book: 'Class 9–10 Democratic Politics', notes: ['Universal adult franchise gives eligible adults the right to vote.', 'Constituencies elect representatives to legislatures.', 'The Election Commission supervises elections to protect fairness.'], questions: [{ id: 'nb-p4q1', questionText: 'Which body conducts and supervises elections in India?', options: ['NITI Aayog', 'Election Commission of India', 'Finance Commission', 'Union Public Service Commission'], correctOption: 1, explanation: 'The Election Commission of India administers elections to Parliament, state legislatures and the offices of President and Vice-President.' }] },
      { id: 'polity-5', order: 5, title: 'Parliament, executive and judiciary', book: 'Class 8–10 Social and Political Life / Democratic Politics', notes: ['Parliament makes laws, controls finance and holds the executive accountable.', 'The executive implements laws and policies.', 'An independent judiciary interprets law and safeguards rights.'], questions: [{ id: 'nb-p5q1', questionText: 'Which institution primarily interprets the Constitution?', options: ['Parliament', 'Judiciary', 'Election Commission', 'Comptroller and Auditor General'], correctOption: 1, explanation: 'Courts interpret the Constitution; the Supreme Court is the highest court in India.' }] },
      { id: 'polity-6', order: 6, title: 'Federalism and constitutional rights', book: 'Class 10 Democratic Politics', notes: ['Federalism divides powers between more than one level of government.', 'The Constitution distributes legislative subjects through lists.', 'Fundamental Rights protect individual liberty, equality and constitutional remedies.'], questions: [{ id: 'nb-p6q1', questionText: 'In a federal system, governmental power is constitutionally divided between:', options: ['Courts and media', 'Different levels of government', 'Political parties only', 'Public and private companies'], correctOption: 1, explanation: 'Federalism is defined by constitutional division of authority between levels such as Union and State governments.' }] },
    ]
  },
  {
    id: 'history', subject: 'History', title: 'Indian History: NCERT Sprint',
    description: 'Move chronologically from sources and early societies to the freedom movement.', sourceUrl: seniorSecondaryUrl,
    chapters: [
      { id: 'history-1', order: 1, title: 'Sources and early societies', book: 'Classes 6–12 History', notes: ['Archaeology uses material remains; inscriptions, coins and texts are historical sources.', 'Sources must be dated, compared and interpreted in context.', 'Prehistory is reconstructed mainly from material evidence.'], questions: [{ id: 'nb-h1q1', questionText: 'Which source is most directly studied by archaeologists?', options: ['Material remains', 'Future forecasts', 'Only modern newspapers', 'Election manifestos'], correctOption: 0, explanation: 'Archaeology studies material remains such as tools, pottery, structures and artefacts.' }] },
      { id: 'history-2', order: 2, title: 'Harappan civilisation', book: 'Class 6 Our Pasts / Class 12 Themes in Indian History', notes: ['Harappan cities show planned streets, drainage and specialised craft production.', 'Seals, weights and trade links reveal organised economic activity.', 'The script remains undeciphered.'], questions: [{ id: 'nb-h2q1', questionText: 'Which feature is strongly associated with Harappan urban planning?', options: ['Grid-like streets and drainage', 'Iron railways', 'Paper currency', 'Gunpowder artillery'], correctOption: 0, explanation: 'Planned streets and elaborate drainage are defining features of several Harappan settlements.' }] },
      { id: 'history-3', order: 3, title: 'States, empires and Ashoka', book: 'Classes 6–12 History', notes: ['The Mauryan Empire was among the earliest large empires in the subcontinent.', 'Ashokan inscriptions communicate policies and dhamma.', 'Edicts are important primary sources for administration and ideas.'], questions: [{ id: 'nb-h3q1', questionText: 'Ashoka’s messages are known chiefly through:', options: ['Printed newspapers', 'Rock and pillar edicts', 'Television archives', 'Copper coins only'], correctOption: 1, explanation: 'Ashoka’s inscriptions on rocks and pillars are primary evidence for his reign and policies.' }] },
      { id: 'history-4', order: 4, title: 'Medieval political and cultural worlds', book: 'Classes 7 and 12 History', notes: ['Medieval history includes changing kingdoms, agrarian systems and networks of trade.', 'Court chronicles reflect particular viewpoints and must be read critically.', 'Bhakti and Sufi traditions shaped religious and cultural expression.'], questions: [{ id: 'nb-h4q1', questionText: 'Why should court chronicles be read critically?', options: ['They are always fictional', 'They often reflect the viewpoint of patrons and authors', 'They contain no dates', 'They were written only in English'], correctOption: 1, explanation: 'Historical sources can carry the perspective and purpose of the people who commissioned or wrote them.' }] },
      { id: 'history-5', order: 5, title: 'Colonial rule and its effects', book: 'Classes 8 and 12 History', notes: ['Colonial policies altered land revenue, forests, crafts and trade.', 'Official records are valuable but reflect administrative priorities.', 'Resistance took many local and regional forms.'], questions: [{ id: 'nb-h5q1', questionText: 'Colonial administrative records should be used with caution because they:', options: ['Never contain facts', 'Reflect official priorities and categories', 'Were all written after Independence', 'Only describe foreign countries'], correctOption: 1, explanation: 'Records are evidence, but their purpose and viewpoint influence what they include.' }] },
      { id: 'history-6', order: 6, title: 'National movement and Independence', book: 'Classes 8 and 12 History', notes: ['The national movement involved mass mobilisation, constitutional debate and diverse leaders.', 'Civil disobedience challenged colonial authority through organised non-cooperation.', 'Independence and Partition were major political and human turning points.'], questions: [{ id: 'nb-h6q1', questionText: 'The Indian national movement is best understood as:', options: ['A single event led by one group', 'A long and diverse anti-colonial movement', 'Only a military campaign', 'A post-1947 development'], correctOption: 1, explanation: 'It developed over decades through many organisations, regions, methods and leaders.' }] },
    ]
  },
  {
    id: 'geography', subject: 'Geography', title: 'Indian Geography: NCERT Sprint',
    description: 'Master physical geography before moving to Indian resources, economy and environment.', sourceUrl: geographyUrl,
    chapters: [
      { id: 'geo-1', order: 1, title: 'Earth, maps and location', book: 'Classes 6–8 Geography', notes: ['Latitude measures north-south position; longitude measures east-west position.', 'Maps use scale, direction and symbols to represent space.', 'The Tropic of Cancer passes through India.'], questions: [{ id: 'nb-g1q1', questionText: 'Latitude is used to measure a place’s position:', options: ['East or west of Greenwich', 'North or south of the Equator', 'Above sea level only', 'Within a time zone only'], correctOption: 1, explanation: 'Latitudes are parallel circles that measure angular distance north or south of the Equator.' }] },
      { id: 'geo-2', order: 2, title: 'Landforms and earth processes', book: 'Classes 6–9 Geography', notes: ['Internal forces create features such as mountains and plateaus.', 'External agents such as rivers, wind and glaciers reshape land.', 'Weathering breaks down rocks at or near the surface.'], questions: [{ id: 'nb-g2q1', questionText: 'Which is an external agent that reshapes landforms?', options: ['River', 'Earth’s core', 'Magnetic field', 'Plate boundary only'], correctOption: 0, explanation: 'Rivers erode, transport and deposit material, thereby reshaping landscapes.' }] },
      { id: 'geo-3', order: 3, title: 'Climate, monsoon and natural vegetation', book: 'Classes 7–10 Geography', notes: ['Weather is short-term atmospheric condition; climate is long-term pattern.', 'India’s monsoon is shaped by seasonal wind reversal and regional factors.', 'Vegetation varies with rainfall, temperature, soil and relief.'], questions: [{ id: 'nb-g3q1', questionText: 'Climate differs from weather because climate describes:', options: ['Hourly rainfall only', 'Long-term atmospheric patterns', 'A single storm', 'Only temperature at noon'], correctOption: 1, explanation: 'Climate is assessed over long periods, while weather describes short-term conditions.' }] },
      { id: 'geo-4', order: 4, title: 'India: physiography and drainage', book: 'Class 9 Contemporary India', notes: ['India contains Himalayas, Northern Plains, Peninsular Plateau, deserts, coasts and islands.', 'River systems shape plains, agriculture and settlement.', 'Drainage patterns depend on relief and geological structure.'], questions: [{ id: 'nb-g4q1', questionText: 'Which physical division is primarily associated with old crystalline rocks?', options: ['Northern Plains', 'Peninsular Plateau', 'Coastal dunes only', 'Coral islands only'], correctOption: 1, explanation: 'The Peninsular Plateau is an ancient stable landmass composed largely of old crystalline rocks.' }] },
      { id: 'geo-5', order: 5, title: 'Resources, agriculture and minerals', book: 'Classes 8–10 Geography', notes: ['Resources are valued through usefulness, technology and accessibility.', 'Soil conservation protects agricultural productivity.', 'Mineral resources are unevenly distributed and require responsible extraction.'], questions: [{ id: 'nb-g5q1', questionText: 'Which practice helps reduce soil erosion on slopes?', options: ['Contour ploughing', 'Removing all vegetation', 'Mining without reclamation', 'Overgrazing'], correctOption: 0, explanation: 'Contour ploughing follows the land’s contour lines and slows runoff on slopes.' }] },
      { id: 'geo-6', order: 6, title: 'Population, industry and sustainability', book: 'Classes 8–12 Geography', notes: ['Population distribution is uneven because physical and economic conditions vary.', 'Industries locate according to raw materials, power, markets, labour and transport.', 'Sustainability balances present use with future needs.'], questions: [{ id: 'nb-g6q1', questionText: 'Which factor can influence industrial location?', options: ['Access to transport', 'Moon phase alone', 'Alphabetical order of cities', 'Only altitude'], correctOption: 0, explanation: 'Transport access is a major location factor alongside inputs, labour, markets and power.' }] },
    ]
  },
  {
    id: 'economics', subject: 'Economics', title: 'Economics: NCERT Sprint',
    description: 'Study development, production, money and public policy in a deliberate order.', sourceUrl: seniorSecondaryUrl,
    chapters: [
      { id: 'eco-1', order: 1, title: 'Development and indicators', book: 'Class 10 Understanding Economic Development', notes: ['Development includes income as well as health, education, equality and security.', 'Per capita income compares average income across populations.', 'Different groups may value different development goals.'], questions: [{ id: 'nb-e1q1', questionText: 'Per capita income is calculated by dividing total income by:', options: ['Number of firms', 'Total population', 'Area of the country', 'Number of banks'], correctOption: 1, explanation: 'It is average income: total income divided by population.' }] },
      { id: 'eco-2', order: 2, title: 'Sectors of the economy', book: 'Class 10 Understanding Economic Development', notes: ['Primary activities use natural resources; secondary activities transform materials; tertiary activities provide services.', 'Organised and unorganised sectors differ in regulation and worker protections.', 'Employment patterns can differ from output shares.'], questions: [{ id: 'nb-e2q1', questionText: 'Manufacturing is generally classified under which sector?', options: ['Primary', 'Secondary', 'Tertiary', 'Household only'], correctOption: 1, explanation: 'Secondary-sector activity processes raw materials into goods.' }] },
      { id: 'eco-3', order: 3, title: 'Money, credit and banking', book: 'Class 10 / Class 11 Economics', notes: ['Money acts as a medium of exchange, unit of account and store of value.', 'Banks accept deposits and provide credit subject to rules and risk.', 'Credit can support production but its terms matter.'], questions: [{ id: 'nb-e3q1', questionText: 'Which function of money removes the need for a double coincidence of wants?', options: ['Medium of exchange', 'Store of rainfall', 'Political representation', 'Natural resource'], correctOption: 0, explanation: 'Money enables exchange without each party needing to want exactly what the other offers.' }] },
      { id: 'eco-4', order: 4, title: 'Government, budget and public goods', book: 'Class 11–12 Economics', notes: ['Governments raise revenue and spend through budgets.', 'Public goods are typically non-rival and non-excludable in consumption.', 'Fiscal choices affect growth, welfare and distribution.'], questions: [{ id: 'nb-e4q1', questionText: 'A government budget is primarily a statement of:', options: ['Rainfall forecasts', 'Expected receipts and expenditure', 'Court judgments only', 'Private household savings only'], correctOption: 1, explanation: 'A budget presents estimated government receipts and expenditure for a financial period.' }] },
      { id: 'eco-5', order: 5, title: 'National income and inflation', book: 'Class 12 Introductory Macroeconomics', notes: ['National income accounting measures aggregate production and income.', 'Real values adjust for price changes; nominal values do not.', 'Inflation is a sustained rise in the general price level.'], questions: [{ id: 'nb-e5q1', questionText: 'Which measure adjusts output or income for changes in prices?', options: ['Nominal value', 'Real value', 'Face value', 'Book value only'], correctOption: 1, explanation: 'Real measures remove the effect of price changes to make comparisons meaningful.' }] },
      { id: 'eco-6', order: 6, title: 'Globalisation and the Indian economy', book: 'Class 10 / Class 12 Economics', notes: ['Globalisation increases cross-border flows of goods, services, capital and ideas.', 'Trade policy affects domestic producers and consumers differently.', 'Economic outcomes depend on institutions, skills and infrastructure.'], questions: [{ id: 'nb-e6q1', questionText: 'Globalisation refers most directly to growing:', options: ['Isolation of national economies', 'Interconnection among economies', 'Only local barter', 'Distance between markets'], correctOption: 1, explanation: 'It involves increased economic interdependence and cross-border exchange.' }] },
    ]
  },
  {
    id: 'science', subject: 'General Science', title: 'General Science: NCERT Sprint',
    description: 'Revise foundational physics, chemistry, biology and ecology for static-GK questions.', sourceUrl: 'https://ncert.nic.in/textbook.php?iesc1=1-13',
    chapters: [
      { id: 'science-1', order: 1, title: 'Matter and its changes', book: 'Classes 6–9 Science', notes: ['Matter has mass and occupies space.', 'Physical changes do not create a new substance; chemical changes do.', 'Particle behaviour explains states of matter and diffusion.'], questions: [{ id: 'nb-s1q1', questionText: 'Which change forms one or more new substances?', options: ['Physical change', 'Chemical change', 'Change of shape only', 'Melting of ice only'], correctOption: 1, explanation: 'A chemical change produces substances with new properties.' }] },
      { id: 'science-2', order: 2, title: 'Force, motion and energy', book: 'Classes 8–10 Science', sourceFocus: 'Class 9 Science: Motion; Force and Laws of Motion; Work and Energy', notes: ['A body may have zero acceleration while moving with constant velocity; speed alone cannot establish that condition.', 'Distance is a scalar path-length; displacement is the shortest directed separation between initial and final positions.', 'The area under a velocity–time graph gives displacement, whereas its slope gives acceleration.', 'For an isolated system, energy changes form; conservation is not a claim that every form remains unchanged.'], questions: [{ id: 'nb-s2q1', type: 'line-detail', questionText: 'A runner completes one full 400 m lap and returns to the starting point in 80 s. Which pair is correct for the lap?', options: ['Distance 400 m; displacement 0 m', 'Distance 0 m; displacement 400 m', 'Distance 400 m; displacement 400 m', 'Distance 0 m; displacement 0 m'], correctOption: 0, explanation: 'The path actually covered is 400 m. Because the final and initial positions coincide, displacement is zero. This tests the textbook distinction rather than a definition recall.' }, { id: 'nb-s2q2', type: 'application', questionText: 'On a velocity–time graph, a straight horizontal segment lies above the time axis. What does this represent?', options: ['Constant positive velocity and zero acceleration', 'Increasing velocity at constant acceleration', 'A body at rest', 'Constant displacement and increasing acceleration'], correctOption: 0, explanation: 'A horizontal velocity–time graph has zero slope, so acceleration is zero; being above the axis means the velocity is positive.' }] },
      { id: 'science-3', order: 3, title: 'Life processes and the human body', book: 'Classes 7–10 Science', notes: ['Nutrition, respiration, transport and excretion sustain organisms.', 'Cells are the basic units of life.', 'Organ systems work together to maintain internal balance.'], questions: [{ id: 'nb-s3q1', questionText: 'What is the basic structural and functional unit of life?', options: ['Tissue', 'Organ', 'Cell', 'Organ system'], correctOption: 2, explanation: 'Cells are the smallest units capable of carrying out life processes.' }] },
      { id: 'science-4', order: 4, title: 'Reproduction, heredity and evolution', book: 'Classes 8–10 Science', notes: ['Reproduction ensures continuity of species.', 'Heredity transmits traits through genetic material.', 'Variation is important for evolution by natural selection.'], questions: [{ id: 'nb-s4q1', questionText: 'Variation within a population is important because it:', options: ['Prevents all reproduction', 'Provides material for evolution', 'Eliminates heredity', 'Stops adaptation'], correctOption: 1, explanation: 'Heritable variation allows populations to adapt over generations.' }] },
      { id: 'science-5', order: 5, title: 'Environment and ecosystems', book: 'Classes 7–12 Science', notes: ['An ecosystem includes organisms and their physical environment.', 'Energy flows through food chains; nutrients cycle through ecosystems.', 'Biodiversity supports ecosystem resilience.'], questions: [{ id: 'nb-s5q1', questionText: 'In a food chain, energy flow is generally:', options: ['Cyclical like nutrients', 'Unidirectional', 'Absent in producers', 'Unlimited at every level'], correctOption: 1, explanation: 'Energy enters mainly through producers and decreases across trophic levels; it does not cycle like matter.' }] },
      { id: 'science-6', order: 6, title: 'Health, disease and public health', book: 'Classes 8–12 Science', notes: ['Disease can arise from infectious agents, genetic factors, environment or lifestyle.', 'Prevention includes sanitation, nutrition, vaccination and informed behaviour.', 'Public health focuses on population-level protection.'], questions: [{ id: 'nb-s6q1', questionText: 'Vaccination primarily helps by:', options: ['Providing permanent nutrition', 'Preparing the immune system to recognise a pathogen', 'Replacing all medical treatment', 'Increasing air pressure'], correctOption: 1, explanation: 'Vaccines train immune responses so the body can respond more effectively to a future exposure.' }] },
    ]
  },
];

export const NCERT_QUESTION_TEXTS = NCERT_TRACKS.flatMap(track =>
  track.chapters.flatMap(chapter => chapter.questions.map(question => question.questionText))
);

export interface NcertClassScope {
  subject: Extract<NcertSubject, 'Polity' | 'History' | 'Geography' | 'Economics'>;
  classLevel: number;
  books: string[];
  learningSequence: string[];
}

// This is the fixed syllabus spine for authoring the chapter-level question bank.
// Units are followed in class order; they are not scraped notes or exercise banks.
export const NCERT_CLASSWISE_SCOPE: NcertClassScope[] = [
  { subject: 'Polity', classLevel: 6, books: ['Social and Political Life I'], learningSequence: ['Diversity', 'Government', 'Rural and urban administration'] },
  { subject: 'Polity', classLevel: 7, books: ['Social and Political Life II'], learningSequence: ['Democracy', 'State government', 'Markets and equality'] },
  { subject: 'Polity', classLevel: 8, books: ['Social and Political Life III'], learningSequence: ['Constitution', 'Secularism', 'Parliament', 'Judiciary', 'Social justice'] },
  { subject: 'Polity', classLevel: 9, books: ['Democratic Politics I'], learningSequence: ['Democracy', 'Constitutional design', 'Electoral politics', 'Institutions', 'Rights'] },
  { subject: 'Polity', classLevel: 10, books: ['Democratic Politics II'], learningSequence: ['Power sharing', 'Federalism', 'Gender and caste', 'Political parties', 'Outcomes of democracy'] },
  { subject: 'Polity', classLevel: 11, books: ['Indian Constitution at Work', 'Political Theory'], learningSequence: ['Constitution', 'Rights', 'Executive', 'Legislature', 'Judiciary', 'Federalism'] },
  { subject: 'Polity', classLevel: 12, books: ['Contemporary World Politics', 'Politics in India Since Independence'], learningSequence: ['Cold War', 'Global institutions', 'Nation-building', 'Planned development', 'India’s external relations'] },
  { subject: 'History', classLevel: 6, books: ['Our Pasts I'], learningSequence: ['Sources', 'Early societies', 'Harappan civilisation', 'Kingdoms and empires'] },
  { subject: 'History', classLevel: 7, books: ['Our Pasts II'], learningSequence: ['Medieval kingdoms', 'Delhi Sultans', 'Mughals', 'Regional cultures'] },
  { subject: 'History', classLevel: 8, books: ['Our Pasts III'], learningSequence: ['Company rule', 'Colonial economy', 'Revolt of 1857', 'National movement'] },
  { subject: 'History', classLevel: 9, books: ['India and the Contemporary World I'], learningSequence: ['French Revolution', 'Socialism', 'Nazism', 'Pastoralists'] },
  { subject: 'History', classLevel: 10, books: ['India and the Contemporary World II'], learningSequence: ['Nationalism', 'Industrialisation', 'Print culture', 'Global world'] },
  { subject: 'History', classLevel: 11, books: ['Themes in World History'], learningSequence: ['Early societies', 'Empires', 'Nomadic cultures', 'Modern revolutions'] },
  { subject: 'History', classLevel: 12, books: ['Themes in Indian History I–III'], learningSequence: ['Harappa', 'Political history', 'Social histories', 'Colonialism', 'Independence'] },
  { subject: 'Geography', classLevel: 6, books: ['The Earth: Our Habitat'], learningSequence: ['Earth in the solar system', 'Maps', 'Domains', 'India'] },
  { subject: 'Geography', classLevel: 7, books: ['Our Environment'], learningSequence: ['Environment', 'Earth interior', 'Air', 'Water', 'Natural vegetation'] },
  { subject: 'Geography', classLevel: 8, books: ['Resources and Development'], learningSequence: ['Resources', 'Land and soil', 'Agriculture', 'Industry', 'Human resources'] },
  { subject: 'Geography', classLevel: 9, books: ['Contemporary India I'], learningSequence: ['India’s location', 'Physiography', 'Drainage', 'Climate', 'Population'] },
  { subject: 'Geography', classLevel: 10, books: ['Contemporary India II'], learningSequence: ['Resources', 'Forests', 'Water', 'Agriculture', 'Minerals', 'Manufacturing'] },
  { subject: 'Geography', classLevel: 11, books: ['Fundamentals of Physical Geography', 'India: Physical Environment'], learningSequence: ['Geomorphology', 'Climate', 'Oceans', 'India’s physical setting'] },
  { subject: 'Geography', classLevel: 12, books: ['Fundamentals of Human Geography', 'India: People and Economy'], learningSequence: ['Population', 'Human activities', 'Resources', 'Transport', 'Planning'] },
  { subject: 'Economics', classLevel: 6, books: ['Social Science foundations'], learningSequence: ['Livelihoods', 'Rural and urban markets', 'Public services'] },
  { subject: 'Economics', classLevel: 7, books: ['Social Science foundations'], learningSequence: ['Production', 'Markets', 'Equality and public facilities'] },
  { subject: 'Economics', classLevel: 8, books: ['Social Science foundations'], learningSequence: ['Resources', 'Industry', 'Human resources', 'Markets'] },
  { subject: 'Economics', classLevel: 9, books: ['Economics'], learningSequence: ['Village economy', 'Human resources', 'Poverty', 'Food security'] },
  { subject: 'Economics', classLevel: 10, books: ['Understanding Economic Development'], learningSequence: ['Development', 'Sectors', 'Money and credit', 'Globalisation'] },
  { subject: 'Economics', classLevel: 11, books: ['Statistics for Economics', 'Indian Economic Development', 'Introductory Microeconomics'], learningSequence: ['Statistics', 'Indian economy', 'Consumer and producer behaviour'] },
  { subject: 'Economics', classLevel: 12, books: ['Introductory Macroeconomics', 'Indian Economic Development'], learningSequence: ['National income', 'Money and banking', 'Government budget', 'External sector'] },
];
