apiVersion: v1
kind: Secret
metadata:
  name: {{ include "preparsenal.fullname" . }}-secrets
  labels:
    {{- include "preparsenal.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: {{ .Values.secrets.supabasePublishableKey | quote }}
  SUPABASE_SERVICE_ROLE_KEY: {{ .Values.secrets.supabaseServiceRoleKey | quote }}
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
  GK_HARVESTER_EMAIL: {{ .Values.secrets.gkHarvesterEmail | quote }}
  GK_HARVESTER_PASSWORD: {{ .Values.secrets.gkHarvesterPassword | quote }}
