replicaCount: 2

image:
  repository: ghcr.io/itzzdev09/preparsenal/web
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
  hosts:
    - host: preparsenal.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: preparsenal-local-tls
      hosts:
        - preparsenal.local

resources:
  limits:
    cpu: 1000m
    memory: 768Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

config:
  nodeEnv: "production"
  supabaseUrl: "https://hopndkiljmarccuhmkdd.supabase.co"
  redisUrl: "redis://preparsenal-redis:6379"

secrets:
  supabasePublishableKey: ""
  supabaseServiceRoleKey: ""
  geminiApiKey: ""
  groqApiKey: ""

redis:
  enabled: true
  image:
    repository: redis
    tag: 7-alpine
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
