apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: preparsenal-ingress
  labels:
    app.kubernetes.io/name: preparsenal
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/limit-rps: "50"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
spec:
  tls:
    - hosts:
        - preparsenal.com
        - www.preparsenal.com
      secretName: preparsenal-tls-secret
  rules:
    - host: preparsenal.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: preparsenal-web
                port:
                  number: 80
    - host: www.preparsenal.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: preparsenal-web
                port:
                  number: 80
